#' kendallRandomPackage: package for exploring air pollution data in Poland.
#'
#' Kendall random walks are Markov processes generated by the Kendall convolution.
#' This package helps simulate and visualize these random walks and associated
#' distributions. It also provides function to fit these distribution to data.
#'
#' @section Important functions:
#' \code{\link{calculateMaxima}} calculates maxima over given period for data important using \code{\link{importGiosFromXLSX}}.
#' \code{\link{fitMultiGEV}} fits GEV distribution using egevd() function from EnvStats package.
#' Resulting table is suitable for further analysis or exploration (like plotting qq-plots, empirical and theoretical CDFs, etc).
#' \code{\link{addMultiKendall}} add empirical and theoretical CDF values and theoretical quantiles of stable kendall distribution
#' for given step distribution and alpha value.
#' \code{\link{kendallRandomApp}} starts a Shiny application that features multiple tools for exploring obtained data,
#' including peak over threshold methods.
#' \code{\link{cdfsKendall}} compare theoretical and empirical CDFs.
#' \code{\link{simulation}} simulates Kendall random walks.
#'
#'
#' @docType package
#' @name kendallRandomPackage
NULL
